[build]
  publish = "www"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/calendar_set/calendar_v8/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/calendar_set/full_ver7/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/calendar_set/calendar_v9/calendar_mobile.html"
  status = 200

