[build]
  publish = "www"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/hosting_index.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v9/hosting_index.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v9/hosting_index_intro.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v10/hosting_index.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v10/hosting_index_intro.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/test/sample20230118_menu_bottom_nonetitle/gradeitionmenu_test2.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/test/sample20230118_menu_bottom_nonetitle/calendar_7.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/test/sample20230118_menu_bottom/gradeitionmenu_test2.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v9/calendar_mobile.html"
  to = "/calendar_set/calendar_v10/calendar_mobile_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v9/calendar_9.html"
  to = "/calendar_set/calendar_v10/calendar_10.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v9/*"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/calendar_set/calendar_v8/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/calendar_set/full_ver7/*"
  to = "/"
  status = 301
  force = true
